// src/graphql/subscription-events.ts
export const SUBSCRIPTION_EVENTS = {
  // ===== TRIP EVENTS =====
  NEW_TRIP_REQUEST: 'NEW_TRIP_REQUEST',
  TRIP_ACCEPTED: 'TRIP_ACCEPTED',
  TRIP_STATUS_CHANGED: 'TRIP_STATUS_CHANGED',
  DRIVER_LOCATION_UPDATE: 'DRIVER_LOCATION_UPDATE',

  // ===== DRIVER EVENTS =====
  DRIVER_STATUS_CHANGED: 'DRIVER_STATUS_CHANGED',
  DRIVER_EARNINGS_UPDATE: 'DRIVER_EARNINGS_UPDATE',

  // ===== ADMIN EVENTS =====
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION',
  SYSTEM_HEALTH_UPDATE: 'SYSTEM_HEALTH_UPDATE',
  SYSTEM_ALERT_CREATED: 'SYSTEM_ALERT_CREATED', // This was missing from your original
  AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',
  ADMIN_STATUS_CHANGED: 'ADMIN_STATUS_CHANGED',
  SYSTEM_CONFIG_UPDATED: 'SYSTEM_CONFIG_UPDATED',

  // ===== SUBSCRIPTION/PAYMENT EVENTS =====
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_STATS_UPDATED: 'SUBSCRIPTION_STATS_UPDATED',
  SUBSCRIPTION_PAYMENT_UPDATE: 'SUBSCRIPTION_PAYMENT_UPDATE',
  SUBSCRIPTION_EXPIRY_NOTIFICATION: 'SUBSCRIPTION_EXPIRY_NOTIFICATION',

  // ===== CUSTOMER EVENTS =====
  CUSTOMER_NOTIFICATION: 'CUSTOMER_NOTIFICATION',

  // ===== GENERAL SYSTEM EVENTS =====
  EMERGENCY_ALERT: 'EMERGENCY_ALERT',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
} as const;

// Type for better TypeScript support
export type SubscriptionEventType =
  (typeof SUBSCRIPTION_EVENTS)[keyof typeof SUBSCRIPTION_EVENTS];
