export const SUBSCRIPTION_EVENTS = {
  // Trip Events
  NEW_TRIP_REQUEST: 'NEW_TRIP_REQUEST',
  TRIP_ACCEPTED: 'TRIP_ACCEPTED',
  TRIP_STATUS_CHANGED: 'TRIP_STATUS_CHANGED',
  DRIVER_LOCATION_UPDATE: 'DRIVER_LOCATION_UPDATE',

  // Admin Events
  ADMIN_NOTIFICATION: 'ADMIN_NOTIFICATION',
  SYSTEM_HEALTH_UPDATE: 'SYSTEM_HEALTH_UPDATE',
  AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',

  // Driver Events
  DRIVER_STATUS_CHANGED: 'DRIVER_STATUS_CHANGED',
  DRIVER_EARNINGS_UPDATE: 'DRIVER_EARNINGS_UPDATE',

  // Customer Events
  CUSTOMER_NOTIFICATION: 'CUSTOMER_NOTIFICATION',

  // System Events
  SYSTEM_CONFIG_UPDATED: 'SYSTEM_CONFIG_UPDATED',
  EMERGENCY_ALERT: 'EMERGENCY_ALERT',
} as const;
